### ISSUE TITLE
How do I stop the Timed Global Chatter?

### ISSUE THREAD

**Issue by Draharak** [cswendrowski/FoundryVtt-Npc-Chatter#1]
So I started it at default speed, that was too fast so I raised the speed. Which just added another layer rather than changing it. So I had a every 5000 milliseconds one running and a every 60000 milliseconds one running. So how do I end the 5000 one?

**Comment by cswendrowski** [comment]
Currently, whoever first set off the macro (probably you) just needs to refresh. In the future I can add a way to unbind existing w/o refreshing
