### ISSUE TITLE
Issue stoppin global chatter

### ISSUE THREAD

**Issue by Whompratt** [cswendrowski/FoundryVtt-Npc-Chatter#10]
I have a scene with several NPCs. When I use:

`game.npcChatter.randomGlobalChatterEvery(15000)`

they chatter as expected. However, using:

`game.npcChatter.turnOffGlobalTimerChatter()`

they don't stop chattering.

Reading the error log in the browser console, the following is displayed after running a macro with the above turnOff command.

`TypeError: message is undefined
    chatBubble http://:30000/modules/polyglot/src/polyglot.js:633
    _call http://:30000/scripts/foundry.js:2496
    call http://:30000/scripts/foundry.js:2481
    say http://:30000/scripts/foundry.js:19547
    async* http://:30000/modules/npc-chatter/npcchatter.js:99
    emit http://:30000/scripts/socket.io.slim.js:6
    onevent http://:30000/scripts/socket.io.slim.js:8
    onpacket http://:30000/scripts/socket.io.slim.js:8
    exports http://:30000/scripts/socket.io.slim.js:8
    emit http://30000/scripts/socket.io.slim.js:6
    ondecoded http://:30000/scripts/socket.io.slim.js:6
    exports http://:30000/scripts/socket.io.slim.js:8
    emit http://:30000/scripts/socket.io.slim.js:6
    add http://:30000/scripts/socket.io.slim.js:6
    ondata http://:30000/scripts/socket.io.slim.js:6
    exports http://:30000/scripts/socket.io.slim.js:8
    emit http://30000/scripts/socket.io.slim.js:6
    onPacket http://:30000/scripts/socket.io.slim.js:6
    setTransport http://:30000/scripts/socket.io.slim.js:6
    emit http://:30000/scripts/socket.io.slim.js:6
    onPacket http://:30000/scripts/socket.io.slim.js:7
    onData http://:30000/scripts/socket.io.slim.js:7
    onmessage http://:30000/scripts/socket.io.slim.js:8
    addEventListeners http://:30000/scripts/socket.io.slim.js:8
    doOpen http://:30000/scripts/socket.io.slim.js:8
    open http://:30000/scripts/socket.io.slim.js:7
    open http://:30000/scripts/socket.io.slim.js:6
    n http:// :30000/scripts/socket.io.slim.js:6
    n http:// :30000/scripts/socket.io.slim.js:6
    connect http:// :30000/scripts/socket.io.slim.js:6
    n http:// :30000/scripts/socket.io.slim.js:6
    n http:// :30000/scripts/socket.io.slim.js:6
    n http:// :30000/scripts/socket.io.slim.js:6
    connect http:// :30000/scripts/foundry.js:6375
    connect http:// :30000/scripts/foundry.js:6374
    create http:// :30000/scripts/foundry.js:6349
    <anonymous> http:// :30000/scripts/foundry.js:7448
    EventListener.handleEvent* http:// :30000/scripts/foundry.js:7447
foundry.js:2499:15
    _call http:// :30000/scripts/foundry.js:2499
    call http:// :30000/scripts/foundry.js:2481
    say http:// :30000/scripts/foundry.js:19547
    <anonymous> http:// :30000/modules/npc-chatter/npcchatter.js:99
    emit http:// :30000/scripts/socket.io.slim.js:6
    onevent http:// :30000/scripts/socket.io.slim.js:8
    onpacket http:// :30000/scripts/socket.io.slim.js:8
    exports http:// :30000/scripts/socket.io.slim.js:8
    emit http:// :30000/scripts/socket.io.slim.js:6
    ondecoded http:// :30000/scripts/socket.io.slim.js:6
    exports http:// :30000/scripts/socket.io.slim.js:8
    emit http:// :30000/scripts/socket.io.slim.js:6
    add http:// :30000/scripts/socket.io.slim.js:6
    ondata http:// :30000/scripts/socket.io.slim.js:6
    exports http:// :30000/scripts/socket.io.slim.js:8
    emit http:// :30000/scripts/socket.io.slim.js:6
    onPacket http:// :30000/scripts/socket.io.slim.js:6
    setTransport http:// :30000/scripts/socket.io.slim.js:6
    emit http:// :30000/scripts/socket.io.slim.js:6
    onPacket http:// :30000/scripts/socket.io.slim.js:7
    onData http:// :30000/scripts/socket.io.slim.js:7
    onmessage http:// :30000/scripts/socket.io.slim.js:8
    (Async: EventHandlerNonNull)
    addEventListeners http:// :30000/scripts/socket.io.slim.js:8
    doOpen http:// :30000/scripts/socket.io.slim.js:8
    open http:// :30000/scripts/socket.io.slim.js:7
    open http:// :30000/scripts/socket.io.slim.js:6
    n http:// :30000/scripts/socket.io.slim.js:6
    n http:// :30000/scripts/socket.io.slim.js:6
    connect http:// :30000/scripts/socket.io.slim.js:6
    n http:// :30000/scripts/socket.io.slim.js:6
    n http:// :30000/scripts/socket.io.slim.js:6
    n http:// :30000/scripts/socket.io.slim.js:6
    connect http:// :30000/scripts/foundry.js:6375
    connect http:// :30000/scripts/foundry.js:6374
    create http:// :30000/scripts/foundry.js:6349
    <anonymous> http:// :30000/scripts/foundry.js:7448
    (Async: EventListener.handleEvent)
    <anonymous> http:// :30000/scripts/foundry.js:7447
`

**Comment by TheBiggerBadderWolf** [comment]
Having the exact same issue here.

**Comment by cswendrowski** [comment]
Seems to be an issue in Polyglot
