### ISSUE TITLE
empty token in selectedChatter()

### ISSUE THREAD

**Issue by DanielBoettner** [cswendrowski/FoundryVtt-Npc-Chatter#11]
While using the **game.npcChatter.selectedChatter()** in a makro there seems to be an issue with getting the token to attach the resulting message from a table to.

The function only works sporadically for me (don't know if this is intended).
The issue seems to be 

https://github.com/cswendrowski/FoundryVtt-Npc-Chatter/blob/532506d28482aee1c6c1fc0f58fafce6c99fe31a/npcchatter.js#L69

As **tableIndex** is generated with a random number. Which than picks a single table from the **elligableTables** with the given index.

https://github.com/cswendrowski/FoundryVtt-Npc-Chatter/blob/532506d28482aee1c6c1fc0f58fafce6c99fe31a/npcchatter.js#L70

This **table** is than used in
https://github.com/cswendrowski/FoundryVtt-Npc-Chatter/blob/532506d28482aee1c6c1fc0f58fafce6c99fe31a/npcchatter.js#L72
to filter npcTokens with the name of **table**.

If you got 

- **Adam Chatter**
- **Eva Chatter**
- **Random Dude Chatter**
- **Random Dude 2 Chatter**

And 

- **Adam**
- **Eva**

as selected tokens. It is likely to happen in 50% that **Random Dude Chatter** or **Random Dude 2 Chatter** are picked as a table in line 70.

When attempting to filter the token in line 72 neither "Random Dude" nor "Random Dude 2" matches and the token will be empty.

If this is an error a solution could be to just pick one of the npcTokens at random from line 63 and call tokenChatter with that token like so (untested).

```
 async selectedChatter() {
    var tables = this.getChatterTables();
    var npcTokens = canvas.tokens.controlled;
    var tokenIndex = Math.floor((Math.random() * eligableTokens.length) + 0);
    
    this.tokenChatter(npcTokens[tokenIndex]);
  }
  
```

**Comment by cswendrowski** [comment]
Good suggestion, closed as of v2.2.0
