### ISSUE TITLE
Can't get this module to work at all (tried 0.7.9, 0.7.10, and 0.8.7)

### ISSUE THREAD

**Issue by rnarducci** [cswendrowski/FoundryVtt-Npc-Chatter#12]
I've tried many different configurations of token names, table names, types of triggers, actors, etc. but I always seem to come back to this error when I try to run a chatter macro. For instance, at its most basic I made a roll table with one entry, called "Bandit Chatter", which I put into the "NPC Chatter" folder, and the token and its actor are called "Bandit". Then I've tried global chatter and specific token chatter, and neither of them work, but the specific token chatter macro (when I specified it to "Bandit", gives me this error).

```
Uncaught (in promise) TypeError: can't access property "name", token is undefined
    eligableTables npcchatter.js:45
    tokenChatter npcchatter.js:45
    anonymous foundry.js line 14629 > Function:5
    anonymous foundry.js line 14629 > Function:6
    _executeScript foundry.js:14631
    execute foundry.js:14592
    _onExecute foundry.js:25580
    jQuery 9
    activateListeners foundry.js:25546
    _render foundry.js:2070
    call_wrapped libWrapper-wrapper.js:466
    <anonymous> libWrapper-error_listeners.js:75
    _render#0 libWrapper-wrapper.js:160
    _render foundry.js:2729
    render foundry.js:2004
    render foundry.js:3223
    callback foundry.js:27952
    render foundry.js:20207
    jQuery 9
    render foundry.js:20204
```

**Comment by TheBiggerBadderWolf** [comment]
I had the exact same issue (and for Bandits no less!) but all working now.

Couple of notes:

- The Scene needs to be the Active one
- Don't forget to set the 'roll table formula' (e.g. 1d16 if you have 16 entries) in the Bandit Chatter roll table.

**Comment by rnarducci** [comment]
> 
> 
> I had the exact same issue (and for Bandits no less!) but all working now.
> 
> Couple of notes:
> 
>     * The Scene needs to be the Active one
> 
>     * Don't forget to set the 'roll table formula' (e.g. 1d16 if you have 16 entries) in the Bandit Chatter roll table.

This fixed it for me!
