### ISSUE TITLE
Idea- Actor: Squad

### ISSUE THREAD

**Issue by NukeMaster0** [cswendrowski/FoundryVtt-Npc-Chatter#7]
Completely unrelated, but I was wondering if you were interested in working on a new type of module where a new actor is made called "Actor: Squad", for example, you have 6 actors in 1 squad, and each actor has 6 HP, so this means 6x6=36 Total, when it reaches 30 HP 1 actor is automatically removed from the token, and the dice damage, "6d6 damage", turns into "5d6 damage", the size would be large and it could create some cool battlefield armies. Thank you.

**Comment by cswendrowski** [comment]
Hey there @NukeMaster0 - although I appreciate the new idea, I'm not currently looking for new things to work on.

Your best bet would be to throw the idea on the Package Ideas board available pinned in this Server's channel: https://discord.gg/ZuHTpWyFHD

**Comment by NukeMaster0** [comment]
Alright, thank you!

**Comment by NukeMaster0** [comment]
Forgot to add, thank you for showing me this, I never thought there was a discord for this.
